server.port=8080

# PostgreSQL Datasource Configuration
# EDIT THESE PLACEHOLDERS for your environment
spring.datasource.url=jdbc:postgresql://localhost:5432/propchk_dev
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.profiles.active=local
